name: Build

on: [push]

jobs:
  run-container:
    runs-on: windows-2022

    env:
      DEVKITPRO: C:\msys64\opt\devkitpro

    defaults:
      run:
        shell: msys2 {0}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Setup MSYS2 Environment
        uses: msys2/setup-msys2@v2

      - name: Updates pacman repos
        run: |
          echo "
          [dkp-libs]
          Server = https://pkg.devkitpro.org/packages

          [dkp-windows]
          Server = https://pkg.devkitpro.org/packages/windows/x86_64/
          " >> /etc/pacman.conf
          pacman-key --recv BC26F752D25B92CE272E0F44F7FD5492264BB9D0 --keyserver keyserver.ubuntu.com
          pacman-key --lsign BC26F752D25B92CE272E0F44F7FD5492264BB9D0
          pacman -Sy --noconfirm
          pacman -Ss dkp-windows
#          wget https://pkg.devkitpro.org/devkitpro-keyring.pkg.tar.xz
#          pacman -U devkitpro-keyring.pkg.tar.xz
#          pacman -Syu --noconfirm
#          pacman -S dkp-windows/devkitARM --noconfirm
