name: Build

on: [push]

jobs:
  run-container:
    runs-on: windows-2022

    env:
      DEVKITARM: C:\devkitpro\opt\devkitpro\devkitARM

    defaults:
      run:
        shell: msys2 {0}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Setup MSYS2 Environment
        uses: msys2/setup-msys2@v2

      - name: Download devkitPro
        run: |
          pacman -Sy --noconfirm wget make
          wget https://wii.leseratte10.de/devkitPro/devkitARM/r63%20%282024-02-01%29/devkitARM-r63-1-windows_x86_64.pkg.tar.zst -O devkitARM-r63-1-windows_x86_64.pkg.tar.zst
          mkdir -p c:\devkitpro
          tar -xvf devkitARM-r63-1-windows_x86_64.pkg.tar.zst -C c:\devkitpro

      - name: Build
        run: |
          cd c:\devkitpro\opt
          ls
          # cd code
          # make
