name: Build

on: [push]

jobs:
  run-container:
#    runs-on: ubuntu-22.04
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          submodules: recursive

#      - name: Build
#        run: |
#          docker run \
#            -v $(pwd):/workspace \
#            -w /workspace \
#            --rm \
#            devkitpro/devkitarm sh -c "cd code && make"

      - name: Download devkitPro 3.0.3
        run: powershell -Command "wget https://github.com/devkitPro/installer/releases/download/v3.0.3/devkitProUpdater-3.0.3.exe -OutFile devkitProUpdater.exe"

      - name: Install devkitPro
        run: ./devkitProUpdater.exe --install --quiet

      - name: Set DEVKITARM Environment Variable
        run: |
          echo "DEVKITARM=C:\devkitPro\devkitARM" >> $GITHUB_ENV

      - name: Build
        run: powershell -Command "cd code; make"

