name: Build

on: [push]

jobs:
  run-container:
    runs-on: windows-2022

    env:
      DEVKITARM: C:\devkitpro\devkitARM

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Setup MSYS2 Environment
        uses: msys2/setup-msys2@v2

      - name: Download devkitPro
        shell: pwsh
        run: |
          wget https://wii.leseratte10.de/devkitPro/devkitARM/r63%20%282024-02-01%29/devkitARM-r63-1-windows_x86_64.pkg.tar.zst -OutFile devkitARM-r63-1-windows_x86_64.pkg.tar.zst
          Expand-Archive -Path devkitARM-r63-1-windows_x86_64.pkg.tar.zst -DestinationPath c:\devkitpro
          cd c:\devkitpro
          dir
          
